---
ID: "4d3409a7-ef50-45bc-b2c1-6a3d9ebddad4"
Parent: "b3a33492-8b0a-4edd-bd1d-1dca79acb61f"
Template: "4d50cdae-c2d9-4de8-b080-8f992bfb1b55"
Path: /sitecore/content/Usergroups/Canada/Ottawa/Presentation/Headless Variants/Promo/Default
BranchID: "37229eac-e94c-4507-b543-6cb1f31294e4"
SharedFields:
- ID: "f6d8a61c-2f84-4401-bd24-52d2068172bc"
  Hint: __Originator
  Value: "{C8F0AA39-7D5A-4BD2-9452-C21B3BFED25D}"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "7a824a94-c36a-4ab4-a574-b2b277e89bca"
